### ISSUE TITLE
practica de tetbox personalizado 

### ISSUE THREAD

**Issue by javiern-778** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-javiern-778#2]
[Práctica Diseño de TexBox personalizado con Visual Studio.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-javiern-778/files/6336312/Practica.Diseno.de.TexBox.personalizado.con.Visual.Studio.pdf)

**Comment by Abraham890** [comment]
Excelente Trabajo 
calificación: 20% de 20%
Califico: Abraham Reyes Ortiz

**Comment by josealfredo79** [comment]
Bien hecho y revisado
